name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./file-management/pom.xml
          mvn clean package -f ./folder-management/pom.xml
          mvn clean package -f ./search-engine/pom.xml

      - name: Docker Build and push for FileManagement
        uses: docker/build-push-action@v4
        with:
          context: ./file-management
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/file-management:latest
            ghcr.io/${{ github.repository }}/file-management:${{ github.ref_name }}
            
      - name: Docker Build and push for FolderManagement
        uses: docker/build-push-action@v4
        with:
          context: ./folder-management
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/folder-management:latest
            ghcr.io/${{ github.repository }}/folder-management:${{ github.ref_name }}
            
      - name: Docker Build and push for SearchEngine
        uses: docker/build-push-action@v4
        with:
          context: ./search-engine
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/search-engine:latest
            ghcr.io/${{ github.repository }}/search-engine:${{ github.ref_name }}
            
