server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: file-management
          uri: http://localhost:8082
          predicates:
            - Path=/files/**, 
        - id: folder-management
          uri: http://localhost:8083
          predicates:
            - Path=/folders/**, 
        - id: search-engine
          uri: http://localhost:8084
          predicates:
            - Path=/searches/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: file-management
          uri: http://fileManagement:8080
          predicates:
            - Path=/files/**, 
        - id: folder-management
          uri: http://folderManagement:8080
          predicates:
            - Path=/folders/**, 
        - id: search-engine
          uri: http://searchEngine:8080
          predicates:
            - Path=/searches/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
