---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-management
  labels:
    app: file-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-management
  template:
    metadata:
      labels:
        app: file-management
    spec:
      containers:
        - name: file-management
          image: username/file-management:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: folder-management
  labels:
    app: folder-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: folder-management
  template:
    metadata:
      labels:
        app: folder-management
    spec:
      containers:
        - name: folder-management
          image: username/folder-management:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-engine
  labels:
    app: search-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-engine
  template:
    metadata:
      labels:
        app: search-engine
    spec:
      containers:
        - name: search-engine
          image: username/search-engine:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: file-management
  labels:
    app: file-management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: file-management


---


apiVersion: v1
kind: Service
metadata:
  name: folder-management
  labels:
    app: folder-management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: folder-management


---


apiVersion: v1
kind: Service
metadata:
  name: search-engine
  labels:
    app: search-engine
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: search-engine

